baseURL: https://luomus.github.io/finbif-blog/
languageCode: en-us
title: Vanilla
theme: "vanilla-bootstrap-hugo-theme"

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: FinBIF Blog
    pre: edit
    url: /post/
    weight: 1
  - name: Tags
    pre: tag
    url: /tags/
    weight: 2
  - name: RSS
    pre: rss
    url: /index.xml
    weight: 3

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
